[package]
name = "system_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
salvo = { version = "0.72",features = ["logging"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
sysinfo = "0.32.0"
serde = "1.0.213"
lazy_static = "1.5.0"